import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextuiProvider } from './nextui-provider'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <NextuiProvider>
          <Navbar />
          <main className='container min-h-screen max-w-6xl'>{children}</main>
        </NextuiProvider>
      </body>
    </html>
  )
}
